version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      # If you want a separate non-root user, uncomment and change these:
      # MYSQL_USER: venu
      # MYSQL_PASSWORD: venu1711
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
